### ISSUE TITLE
Web-pods: technical preview 1

### ISSUE THREAD

**Issue by gcarcassi** [diirt/diirt#44]
Provide a first deployable prototype, with specs for the protocol, the type serialization and the javascript client.

Out of scope:
* security (don't know how to do it yet)
* widgets (will just be there to showcase the pipeline)

In scope:
* Finalize the protocol spec and implementation
* Finalize the JSON serialization
* Finalize the javascript client spec and implementation
* Some examples

**Comment by shroffk** [comment]
Closing this and creating a new Issue to address individual topics
