### ISSUE TITLE
Local Enum PVs

### ISSUE THREAD

**Issue by willrogers** [diirt/diirt#62]
We have a need for local enum PVs at Diamond.  I've got a patch for PVManager that we've been using for a few weeks, so I would like to port this to Diirt.  Is everyone happy to do this?  I'd like to get this included in our 4.2 build of CS-Studio.

We should be able to address #59 at the same time if necessary.

@shroffk @berryma4 @kasemir

**Comment by shroffk** [comment]
Sure, sounds good to me.
Can you make a pull request to the ControlSystemStudio/diirt forked repo
Currently I am using that fork to do all the development on, which will then be merged back into this main repo once ready for release.

**Comment by kasemir** [comment]
Yes, good idea.

**Comment by shroffk** [comment]
@willrogers can this be closed?

**Comment by willrogers** [comment]
Yep all done.
