### ISSUE TITLE
Update caj to 1.1.15

### ISSUE THREAD

**Issue by ralphlange** [diirt/diirt#66]
diirt/support/ca/pom.xml depends on caj 1.1.14

@msekoranja says that it is generally suggested to update to 1.1.15

**Comment by shroffk** [comment]
I will update the diirt support.
Does this necessitate an immediate release? or would it be fine so longg as the next diirt release uses caj 1.1.15

**Comment by ralphlange** [comment]
Diirt release is when you throw a shovel, right?
Next shovel is fine.

**Comment by shroffk** [comment]
Not sure I understand this particular figure of speech, but currently the releases are happening of the the cs-studio fork of diirt (the last one being the 3.0.2...I am still arguing with Eric over weather in addition to the new p2 repo sitory releases we should also release to the maven central repo too)

At some point when there is some more breathing room, the form will be merged back into the main repository and releases will resume from the main diirt branch.

**Comment by ralphlange** [comment]
Fork of diirt also sounds good.
Sorry, but "release of diirt" made me think of an excavator/dredged. Can't help it.

**Comment by shroffk** [comment]
Well the shovel has been thrown and the diirt released...
caj updated to 1.1.5
pvdata updated to 5.0.3
pvaccess updated to 4.1.3
This will be part of the 3.1.4 release

**Comment by ralphlange** [comment]
caj update should read 1.1.15 ??

**Comment by ralphlange** [comment]
EPICS V4 is preparing the 4.6.0 release right now (with new versions of pvData, pvAccess) - the -rc1 release candidate is coming out next week.
Bad timing?

**Comment by shroffk** [comment]
>> caj update should read 1.1.15 ??
yes thankfully it was only a typo in the git comment, the pom and the change logs are correctly pointing to 1.1.15

>> new v4 release....
This really sucks, while it is not difficult to update diirt to point to the new release, getting it up the entire stack is....well...
Oh well, I will do a new release.

Can we close this ticket and open a new one when the new v4 release is out?
