### ISSUE TITLE
Time based Unit tests fail when run from timezone other than EST

### ISSUE THREAD

**Issue by shroffk** [diirt/diirt#67]
The time strings against which the tests are run are hard coded to use EST which causes them to fail when run from any time zone other than that.
Fixing this by replacing the hardcoded string with a string created using the local system set timezone

**Comment by shroffk** [comment]
Fixed all the time based unit tests except the daylight saying ones which while the still work for EST do not work for other timezones which might have different daylight saving rules...thus they are disabled.

**Comment by gcarcassi** [comment]
Kunal, we went to a lot of trouble to add those tests. Why don't you just skip them if you are in a different timezone?

**Comment by shroffk** [comment]
Ok, I agree they do look like fairly involved and complicated tests....and certainly necessary for correct plotting.

TODO: 
1. conditionally enable the daylightsaying tests after checking the timezone. If the Timezone is EST rung the tests, else skip it.

2. Additionally, it would be ideal is these test could be run with a European example of daylight savings.

**Comment by shroffk** [comment]
Adding the tests back with conditional run checks
