### ISSUE TITLE
VImage needs data beyond byte[]

### ISSUE THREAD

**Issue by kasemir** [diirt/diirt#68]
VImage uses byte[] for data.
Now that V4 NTNDArray has been defined and is about to be published by Area Detector, VImage needs to grow to capture the essential image information.
At a minimum, SNS would need support for unsigned 16 bit.
(Could promote to 32 bit Java (signed) interger type.
 Or keep in Java short, but add signed/unsigned flag to VImage so that image widgets can interprete the data accordingly)

**Comment by kasemir** [comment]
One solution would be to change `VImage::getData()` from returning `byte[]` to returning `ListNumber`.

**Comment by kasemir** [comment]
#### Update from hangout w/ Kunal, Eric, Kay

On a brach of https://github.com/ControlSystemStudio/diirt, we'll update `VImage` to return a `ListNumber` instead of `byte[]` for the data.

The `ListNumber` will wrap the actual `byte[]`, `short[]`, `int[]`, `long[]`, `float[]`, `double[]` from the NTNDArray/value. In case client code needs to know what the actual data type was, it can use `instance ListLong` etc. to check for the basic type.

Unsigned data is handled by up-converting it to the next higher (signed) Java type. If the NTNDArray received via pvAccess sends an unsigned byte, the `VImage` will have a `ListShort` for data to hold the values 0..255. If the `NTNDArray` sends an unsigned short, the `VImage` will have a `ListInt` for data to hold the values 0..0xFFFF. Unsigned int can be updated to a `ListLong`. For unsigned long data (32 bit), we're not sure how to upcast it, maybe to double? For now, we won't do anything about unsigned long. We pass it on as a long[], because in practice the use of unsigned long is expected to be insignificant.

`ListNumbers` might get a new helper function for turning the `VImage` `ListNumber` data into a `byte[]` suitable for use as raw AWT or SWT image memory, same was as the existing BOY VImage widget constructs the in-memory image.

**Comment by kasemir** [comment]
Notes from hangout, plan:
https://docs.google.com/document/d/18RfNiD99l3oi30ulaAmvruMcJgc85xpzpX05xCU9DB4/edit?usp=sharing﻿

**Comment by shroffk** [comment]
This work has been completed on the following branch and is ready for testing
https://github.com/ControlSystemStudio/diirt/tree/VImage

**Comment by shroffk** [comment]
https://github.com/shroffk/cs-studio/commit/def1ab088f02d2c099aae9e5cd8b82e05c1f8345

The patch which updated the VImage support provided via pvmanager in cs-studio.

**Comment by kasemir** [comment]
In https://github.com/ControlSystemStudio/cs-studio, created branch diirt_68_VImage to update vtype.pv so it can handle NTNDArray with short, int and long arrays.

**Comment by kasemir** [comment]
I'm for now using that with the example image server from the V4 training, which I've updated to serve 16 bit instead of the original 8 bit images (https://github.com/kasemir/EPICSV4Sandbox).

**Comment by kasemir** [comment]
Yes, thanks!
