### ISSUE TITLE
Managing the WorkerPool size

### ISSUE THREAD

**Issue by shroffk** [diirt/diirt#69]
currently the worker pool size is set to the maximum number of processors available to the JVM -1. This works well in most cases however on some of our gateway machines people are running cs-studio with a workerpool of 321 threads.
I would like to add a jvm property to define an upperlimit on this

```
private static final ScheduledExecutorService workerPool = Executors.newScheduledThreadPool(
			Math.max(1,
					System.getProperty("MaxWorkerPoolSize") != null
							? Integer.valueOf(System.getProperty("MaxWorkerPoolSize"))
							: Runtime.getRuntime().availableProcessors() - 1),
			org.diirt.util.concurrent.Executors.namedPool("PVMgr Worker "));
```

Is this ok with everyone
- [x] NSLS2
- [x] Diamond @willrogers
- [x] FRIB @berryma4
- [x] ITER @utzeln

I will make this change on the cs-studio fork.

**Comment by willrogers** [comment]
I don't think I can click this checkbox but that looks fine for me.
