### ISSUE TITLE
Waiting 1s can be too low in heavy loaded systems

### ISSUE THREAD

**Issue by claudio-rosati** [diirt/diirt#77]
Inside the `FileWatcherFileSystemServiceTest.udpateFile` test, waiting 1s can be too low in heavy loaded systems.
On my Mac, during a background backup running, I had to increase it to 10s or more to be sure the file change is correctly propagated to DIIRT service.

**Comment by shroffk** [comment]
relevant discussion for possible solutions

> add a file modification listener in the test itself and check the counter after we are sure the jvm has sent the notification
> or simply increase the timeout (which is what I prefer since it is simpler)

for the time being we have chosen the latter for the sake of simplicity
