### ISSUE TITLE
Make time format configurable

### ISSUE THREAD

**Issue by shroffk** [diirt/diirt#79]
With the migration to java.time a lot of the time utility classes were replaced by those available in the jdk8, currently the timeFormatter, when used, is hardcoded, this should be configurable.
A new configuration file will be added to define the default timeformatter for diirt.

**Comment by boryto** [comment]
Created pull request - #80

**Comment by shroffk** [comment]
can this be closed, it is merged and will be part of the next release

**Comment by boryto** [comment]
Yes, please close it. I have no permissions for close.
