### ISSUE TITLE
Update CI jobs or move to travis

### ISSUE THREAD

**Issue by shroffk** [diirt/diirt#81]
The CI jobs on https://openepics.ci.cloudbees.com/view/Diirt/ have been disabled for awhile now.
As preparation for the next release we should either enable them or set up other CI build jobs.

@berryma4

**Comment by berryma4** [comment]
I agree, let's move to TravisCI

**Comment by shroffk** [comment]
Added basic file 
https://github.com/diirt/diirt/commit/cf5176c73507f0bafc8250784a3b9d6b8427229d

**Comment by berryma4** [comment]
I added a build status button to the readme:
0af9107a5067bb8c706989c62af16c0b4a5073f4

**Comment by shroffk** [comment]
ah ha ha...I was adding the exact same thing
